### PR TITLE
Add fedora support to GetOSVersion

### PR DESCRIPTION
**Pull request by janiskemper**
Add Fedora support to the function GetOSVersion and unit test.

### CODE REVIEW

**Review by vteratipally — APPROVED** [review]

**Comment by Random-Liu** [comment]
Do you want to rebase the change?

**Comment by janiskemper** [comment]
Can this be re-opened? Was I supposed to do something?

**Comment by vteratipally** [comment]
> Can this be re-opened? Was I supposed to do something?

Yes, the change needs to be rebased.

**Pull request closed without merging**
