### PR TITLE
Create multi-arch image

### LINKED ISSUE #586: multi-arch image
I was excited to see arm64 added but when I pull k8s.gcr.io/node-problem-detector/node-problem-detector:v0.8.9 I still get `standard_init_linux.go:228: exec user process caused: exec format error`

### PR DESCRIPTION
**Pull request by acumino**
Fixes #586

### CODE REVIEW

**Comment by acumino** [comment]
@dchen1107 Can we have a new release of NPD with multi-arch image?

**Comment by Random-Liu** [comment]
/lgtm

And sure we can!

**Comment by ialidzhikov** [comment]
> And sure we can!

Any updates on this one @Random-Liu ? We are looking forward to it! :)

**Comment by vteratipally** [comment]
There is an issue with building the image. Working on fixing it. I will post the error in a while.

**Pull request merged**
