### PR TITLE
Change to using new dependency name for osreleaser

### LINKED ISSUE #626: Account takeover of vendored dependency
The github account @cobaugh no longer exists, and was taken over by a security researcher. Please replace this dependency before a vendor update can accidentally pull in a compromised version.

### PR DESCRIPTION
**Pull request by mx-psi**
### What does this PR do?

Changes `github.com/cobaugh/osrelease` to `github.com/acobaugh/osrelease`. 

Fixes #626.

### Additional notes

﻿To do this I
1. changed the name in go.mod and the Go code that used it,
2. ran `go mod tidy -go=1.15` and
3. ran `go mod vendor`.

Step 3 added another vendored dependency unrelated AFAIK to this change.

### CODE REVIEW

**Comment by tallclair** [comment]
Friendly ping. I'd like to see this merged.

**Comment by mx-psi** [comment]
Anything I can do to get this merged?

**Comment by mx-psi** [comment]
It seems unlikely to me that the failing tests are related to the contents of this PR. Can someone with more knowledge of the project assess if these are related and, if so, how to fix them? cc @tallclair ?

**Pull request merged**
