### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by thecantero**
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/node-problem-detector/57)

### CODE REVIEW

**Comment by andyxning** [comment]
@thecantero Could you please sign the cla? :)

**Comment by andyxning** [comment]
/lgtm

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/node-problem-detector/57#-:-K_2A5hmwOodN6G_5PaW:b-8ks5qa)*

**Comment by andyxning** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/node-problem-detector/57)*

**Comment by Random-Liu** [comment]
/lgtm

@andyxning Thanks for your help!

**Pull request merged**
