### PR TITLE
Update node-problem-detector.yaml

### PR DESCRIPTION
**Pull request by douglasmakey**
Hi All,

I was having a timeout issue when I was trying to use a custom plugin using NPD v0.8.6. I noticed there is a new version with the fix. 

The Manifest should have the last available version.

### CODE REVIEW

**Comment by Random-Liu** [comment]
The travis build should have been fixed.

I don't seem to have permission to trigger a rerun, can you try whether you have permission for it? @douglasmakey

**Comment by Random-Liu** [comment]
@douglasmakey You may want to click into travis, and see whether there is rebuild option.

**Comment by douglasmakey** [comment]
I guess I can't.

Screen Shot 2021-05-04 at 4 08 51 PM

**Comment by Random-Liu** [comment]
Let's try close and reopen the PR then.

**Pull request merged**
