### PR TITLE
Vendor the "right" fsnotify

### PR DESCRIPTION
**Pull request by freeformz**
This is the version that hpcloud/tail vendors

### CODE REVIEW

**Comment by freeformz** [comment]
See #7

**Comment by Random-Liu** [comment]
@freeformz IIUC, this should eliminate the dependency on `/sys/unix`, right? Could you also clean that? :) Thanks a lot!

**Comment by freeformz** [comment]
@Random-Liu done.

**Comment by Random-Liu** [comment]
@freeformz Quick question. I'm not quite familiar with Godeps. Could you explain the last 2 commits a bit? The first 2 LGTM.

**Comment by Random-Liu** [comment]
All right, understood the 3rd one. https://github.com/tools/godep/blob/master/Changelog.md
Can you explain the last commit a bit?

**Comment by freeformz** [comment]
Before v71 we didn't preserve permissions of the files copied in, now we do. This is particularly important for executable files.

The last one doesn't really matter that much, it looks like a more exact tag was added at some point and we're now picking it up.

**Comment by Random-Liu** [comment]
@freeformz Thanks a lot! LGTM!

**Pull request merged**
