### PR TITLE
Install util-linux to have lsblk binary

### LINKED ISSUE #420: official image does not contain lsblk binary
we run npd 0.8.0 from: k8s.gcr.io/node-problem-detector:v0.8.0

but every some seconds we have the following error log entries:

```
node-problem-detector-q99zr node-problem-detector E0325 10:30:02.459512       1 disk_collector.go:145] Error calling lsblk
```

Checking inside the container confirms this.
I am happy to raise a PR to fix this.

### PR DESCRIPTION
**Pull request by majst01**
This addresses #420

### CODE REVIEW

**Comment by majst01** [comment]
@xueweiz any estimates when there is a new release of NPD ?

**Comment by xueweiz** [comment]
@Random-Liu Do we have plan to release NPD any time soon?

---
By the way, if the release is blocking you from picking up the fix, you could consider build a docker image on top of the released NPD image, and install lsblk in it. Please let me know if this still cannot unblock you.

**Comment by majst01** [comment]
Yes of course i will do if a release of NPD will take several weeks, but if its in the foreseeable future i will wait.

**Comment by xueweiz** [comment]
I guess we might wait for a while before doing the next NPD release, because there are not many major features/fixes recently.

**Pull request merged**
