### PR TITLE
Add multiarch support and docker manifests

### LINKED ISSUE #135: ARM version
Is a multi-architecture version (ARM) possible?

### PR DESCRIPTION
**Pull request by Sh4d1**
Fixes #135 

This is #250 rebased on master with some additional fixes to make it work. (I was planning on making a PR on the fork of @mkumatag but he has to rebase his branch in ordre to merge it so creating a new PR sounded easier. (So most of the work was done by @mkumatag :sweat_smile:)

Fixes: kubernetes/kubernetes#73364

### CODE REVIEW

**Comment by Sh4d1** [comment]
@Random-Liu @dchen1107 possible to get an ok to test?

**Comment by Sh4d1** [comment]
Hmm it seems the failure are quite random :thinking:

**Comment by Sh4d1** [comment]
So blocked by kubernetes/test-infra#14091 for now

**Comment by Sh4d1** [comment]
@andyxning so according to kubernetes/test-infra#14091 we need to setup GCB. Is this okay? If yes I'll add a `cloudbuild.yaml` and submit a PR to test-infra as well as creating a bucket on k8s.gcr.io.

**Comment by Sh4d1** [comment]
@dchen1107 @Random-Liu I'll ping you too 😅

**Comment by Sh4d1** [comment]
So I'll setup gcb and cross compiling next week :)

**Comment by Sh4d1** [comment]
It seems really hard to do it in Prow (can't statically cross-compile thanks to go-systemd). I'll try to get some GCB runners for this project!

**Comment by Sh4d1** [comment]
Once https://github.com/kubernetes/test-infra/pull/16790 is merged, it should be good to go 
/cc @xueweiz

**Comment by Sh4d1** [comment]
@Random-Liu @xueweiz all good for you?
/cc @mkumatag

**Comment by xueweiz** [comment]
@Sh4d1 Hi Patrik, sorry I don't have many context on this PR. But looks like other reviewers are busy these days, I'll try to find some time in these 1-3 days to learn more about the context and review this PR.

**Comment by Sh4d1** [comment]
@xueweiz yes no problem :)
For the context : today npd is only built for amd64. And this PR intends to allow to build for multiple arch. 
Cross build does not work so we need to use qemu, and to do so we need to use cloubuild :) 
Everything should be done on the cloud build side, but it will also imply a new release process though (the new one which is recommended). 
I can link the different PRs and doc if you want!

**Comment by Sh4d1** [comment]
Basically it's to use https://github.com/kubernetes/test-infra/blob/master/config/jobs/image-pushing/README.md and https://github.com/kubernetes/k8s.io/blob/master/k8s.gcr.io/README.md 

Work done:
https://github.com/kubernetes/test-infra/pull/16790
https://github.com/kubernetes/k8s.io/pull/552

**Comment by xueweiz** [comment]
Thanks for the explanation! I have never done multiarch work before, so I need to do some homework to learn about how other k8s projects support this.

> Cross build does not work so we need to use qemu, and to do so we need to use cloubuild :)

This is the part I would need to learn more about :) Do you know any other k8s projects doing similar thing? If so, could you provide some reference (Makefile, PR, etc)? Then I could study them as a reference.

Thanks!

**Comment by Sh4d1** [comment]
I've done quite the same with https://github.com/kubernetes-sigs/apiserver-network-proxy/pull/38 and https://github.com/kubernetes-sigs/metrics-server/pull/467

Not sure how other are doing it (iirc I took some inspiration from another k8s project, but can't recall which one :sweat_smile: ) 

Cross build is not working with npd because of systemd dependencies and some CGO code.

But the basics of multi arch is to build each arch and then create a docker manifest (with the docker manifest) command and just push it :)

**Comment by xueweiz** [comment]
This is great! Thanks for the pointers. I'll update (hopefully soon) when I finishes the homework.

/assign @xueweiz

**Comment by Sh4d1** [comment]
Just ping if you have any questions 😄

**Comment by mkumatag** [comment]
> @Random-Liu @xueweiz all good for you?
> /cc @mkumatag

code seems okay to me,

**Comment by nvtkaszpir** [comment]
fixes #135

**Comment by Sh4d1** [comment]
@xueweiz any news?

**Pull request closed without merging**
