### PR TITLE
Bump some major dependencies to latest versions

### LINKED ISSUE #487: Bump opencensus-go-exporter-stackdriver
We should consider bumping `contrib.go.opencensus.io/exporter/stackdriver` package to the latest (0.13.4) from the current v0.12.5.

There's a few changes that look particularly impactful in terms of performance (I think):

* https://github.com/census-ecosystem/opencensus-go-exporter-stackdriver/commit/9366d3634e70bea85a87d33f6f23e5f9c673f8fa
* https://github.com/census-ecosystem/opencensus-go-exporter-stackdriver/pull/179/files#

### PR DESCRIPTION
**Pull request by karan**
Fixes #487

Tested with `make test`.

### CODE REVIEW

**Comment by wangzhen127** [comment]
/lgtm
/hold

Feel free to unhold after @vteratipally take a look.

**Comment by karan** [comment]
/hold cancel

The test will still fail until https://github.com/kubernetes/kubernetes/issues/95955 is closed.

**Pull request merged**
