### PR TITLE
Detect corrupt docker overlay2

### PR DESCRIPTION
**Pull request by wangzhen127**
This PR adds one more custom plugin that can detect corrupt docker overlay2 issue.

### CODE REVIEW

**Comment by wangzhen127** [comment]
This PR depends on a previous PR https://github.com/kubernetes/node-problem-detector/pull/223. Only `config/docker-monitor-counter.json` is the new change. This PR should merge after #223 is merged first.

/assign @Random-Liu 
/cc @jiayingz

**Comment by Random-Liu** [comment]
LGTM

**Comment by wangzhen127** [comment]
Rebased. PTAL

/hold cancel

**Pull request merged**
