### PR TITLE
Release v0.8.16

### PR DESCRIPTION
**Pull request by hakman**
This should address the missing `log-counter` binary.

/cc @vteratipally @pacoxu @MartinForReal 
/assign @vteratipally

### CODE REVIEW

**Comment by pacoxu** [comment]
I triggered a test in Kuberentes CI https://github.com/kubernetes/kubernetes/pull/123550.
- https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/123550/pull-kubernetes-e2e-gce/1762706028115267584

**Comment by hakman** [comment]
> The test passed for NPD: flake for https://storage.googleapis.com/k8s-triage/index.html?test=Networking%20Granular%20Checks%3A%20Services%20should%20update%20endpoints%3A%20http.

@pacoxu Test failed on 1 unrelated test. I think we are good to go.
/unhold

**Review by mrunalp — APPROVED** [review]

**Comment by vteratipally** [comment]
could you please draft a release notes in one of the comments, it would be useful for all us. It is hard to track the changes after the release.

**Comment by hakman** [comment]
@vteratipally It is pretty hard to draft such release notes.
The release trigger drafts it from the PR titles and depends on how good the titles are.

**Pull request merged**
