### PR TITLE
instance field added to prometheus metrics

### PR DESCRIPTION
**Pull request by bilalcaliskan**
#### Which issue(s) this PR fixes:
this pr solve issue #532  .

#### What this PR does / why we need it:
This PR exposes instance field on exported prometheus metrics. We need it to collect the metrics from external Prometheus and create alerting rules with more information about on which instance there is a problem affecting the node. 

#### Special notes for your reviewer:
None.

### CODE REVIEW

**Comment by bilalcaliskan** [comment]
just signed the sla

**Comment by Random-Liu** [comment]
Not quite familiar with Prometheus. When collecting the metrics from a specific node, you already know where they come from, is it possible to attach some information during that?

**Comment by bilalcaliskan** [comment]
@Random-Liu This PR actually does that. Usually exporters export metrics with additional instance field, so you can know which metric came from which instance when you collected them to Prometheus.

**Comment by bilalcaliskan** [comment]
@Random-Liu my previous answer was completely wrong, sorry for the wrong information. After i have collected exporter metrics from prometheus-operator, i have noticed that prometheus adds metadata tags as you mentioned earlier. So this PR is not neccessary at all.

**Comment by bilalcaliskan** [comment]
My mistake, this PR still needed because without this PR, exporter exports metrics in the below format:
```
problem_gauge{container="node-problem-detector", endpoint="exporter", instance="10.233.73.28:20257", job="node-problem-detector", namespace="node-problem-detector", pod="node-problem-detector-fbzjc", reason="AUFSUmountHung", service="node-problem-detector", type="KernelDeadlock"}
```

`instance` field here is the ip address of the pod, so we need the ip address of the node.

**Comment by bilalcaliskan** [comment]
@xueweiz hey! Could you review that PR, this enhancement will make our life easier.

**Comment by bilalcaliskan** [comment]
@wangzhen127 @xueweiz @Random-Liu did you take a chance to review the code changes?

**Comment by vteratipally** [comment]
could you please address test failure

**Comment by bilalcaliskan** [comment]
@vteratipally working on it 👍

**Comment by bilalcaliskan** [comment]
@vteratipally @Random-Liu The problem was i forgot to change e2e tests. I have noticed that tests were failing because current e2e tests were looking for some metric like below:
```
problem_gauge{reason="AUFSUmountHung",type="KernelDeadlock"}
```
But with the update of [updated code](https://github.com/bilalcaliskan/node-problem-detector/blob/master/cmd/nodeproblemdetector/node_problem_detector.go#L52), new exporter exports the metrics like below:
```
problem_gauge{instance="localhost",reason="AUFSUmountHung",type="KernelDeadlock"}
```

It was hard to debug the problem so i had messed up the git history a little bit. I did some modifications on current e2e tests but somehow i could not make it pass the pull-npd-e2e-test phase so i give up for now. Somehow `pull-npd-e2e-test` still fails but i do not think it's about current e2e tests, [it looks like a network problem.](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/node-problem-detector/533/pull-npd-e2e-test/1369876203195863040#1:build-log.txt%3A233)

I would appreciate if anyone else can implement [that pull request](https://github.com/kubernetes/node-problem-detector/issues/532).

**Comment by vteratipally** [comment]
/test pull-npd-e2e-test
--

**Comment by bilalcaliskan** [comment]
@vteratipally awkward logs again and again. I also have asked for help on [Slack](https://kubernetes.slack.com/archives/CJA25LM6D/p1617350999004100).

**Comment by vteratipally** [comment]
I have tested the patch locally as well, not sure why this is still failing. Seems fine on my end

**Comment by bilalcaliskan** [comment]
It's really weird problem i guess. I can not find anything about the real problem but somehow it looks like the problem is not about the code as you mentioned. There is no logical explanation that 3 tests are passing and 2 tests are failing, sadly logs of the failing tests are not addressing anything about the patched code.

**Comment by vteratipally** [comment]
could you please squash all the commits.

**Comment by vteratipally** [comment]
the test failed because of the build error. Might have missed some of the changed code during rebase,

**Comment by bilalcaliskan** [comment]
@vteratipally yes, on the rebased code i have missed the refactor newly added test file, should be fixed with the last commit :+1:

**Comment by bilalcaliskan** [comment]
@vteratipally stuck at the [same place](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/node-problem-detector/533/pull-npd-e2e-test/1379563125270908928#1:build-log.txt%3A222), not so surprised :) Is there a way to increase ssh connection timeout, perhaps it may help.

**Comment by vteratipally** [comment]
https://github.com/kubernetes/node-problem-detector/blob/master/test/e2e/lib/ssh/ssh.go  this is the file they use it for ssh tests

**Comment by bilalcaliskan** [comment]
@vteratipally thanks for the help. But npd uses [k8s.io/kubernetes/pkg/ssh](https://github.com/kubernetes/kubernetes/tree/master/pkg/ssh) as ssh library and ssh dial timeout set in [right here](https://github.com/kubernetes/kubernetes/blob/master/pkg/ssh/ssh.go#L166). I think there is no way to override that timeout value in node problem detector.

**Comment by bilalcaliskan** [comment]
I have created [that issue](https://github.com/kubernetes/kubernetes/issues/100918) on https://github.com/kubernetes/kubernetes and someone opened [that PR](https://github.com/kubernetes/kubernetes/pull/100955).  After that PR merged, i will be able to debug by increasing ssh timeout.

**Comment by bilalcaliskan** [comment]
there is a discussion about the ssh package usage in [here](https://github.com/kubernetes/kubernetes/issues/100918). Hope that it will solve the problem.

**Comment by Random-Liu** [comment]
> instance field here is the ip address of the pod, so we need the ip address of the node.

Is it the IP address of the NPD pod? If you need the node IP, can you just run NPD in the host network?

**Comment by bilalcaliskan** [comment]
@Random-Liu sorry for the late answer. We also thought about that method but running a pod with hostNetwork is not a very secure method. I guess exposing the instance node ip address is more secure and best practice in that case.  By the way currently we are running our node-problem-detector deployments with hostNetwork but other approach would be great.

**Pull request closed without merging**
