### PR TITLE
optimize netcollector implementation and custom `/proc` mount path

### PR DESCRIPTION
**Pull request by oif**
Improvements:

- net collector metrics: optimized register and record
- custom `/proc`: supports mount host `/proc` with a custom path into the NPD container

### CODE REVIEW

**Comment by Random-Liu** [comment]
@vteratipally Will rely on you for the review. :)

**Review by vteratipally — APPROVED** [review]

**Comment by oif** [comment]
@wangzhen127 Hello, waiting for your approval.

**Comment by oif** [comment]
@Random-Liu would you review this PR at your ease?

**Comment by oif** [comment]
just wait https://github.com/kubernetes/node-problem-detector/pull/647 to resolve test issues

**Comment by oif** [comment]
@vteratipally may keep going?

**Comment by oif** [comment]
@vteratipally just rebase master branch, tests working

**Pull request merged**
