### PR TITLE
Build multi-arch image

### PR DESCRIPTION
**Pull request by xinydev**
Fixes: https://github.com/kubernetes/node-problem-detector/issues/586 

Because `k8s.gcr.io/debian-base-amd64:v2.0.0` does not support multiple architectures, I use `debian:buster` instead.

buildx can not export multiple architectures image to docker, https://github.com/docker/buildx/issues/59 ,So we directly push the image to the registry

If you want to build this locally, make sure run the following command first , otherwise you may get a error `error: multiple platforms feature is currently not supported for docker driver. Please switch to a different driver (eg. "docker buildx create --use")`

```
# run this before build locally 
# If you build this on Github Action, Add a step `docker/setup-buildx-action@v1` instead 
sudo docker buildx create --name builder --driver docker-container --driver-opt image=moby/buildkit:master
```

``` sh 
docker manifest inspect xinydev/node-problem-detector:v0.8.9

{
   "schemaVersion": 2,
   "mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
   "manifests": [
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 1368,
         "digest": "sha256:de9f30d2f0aea0b983db7d437a1d58cfd8daa7a2c264e7687687f31e87fd7826",
         "platform": {
            "architecture": "amd64",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 1368,
         "digest": "sha256:fb2e84e713932539deb10e5c2773a96c93b6cb334a01b05c60eee175b11a8d91",
         "platform": {
            "architecture": "arm",
            "os": "linux",
            "variant": "v7"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 1368,
         "digest": "sha256:b0dd91c795b9cb77aec2308d35086c80cb40a1690d02b964ff92f2e4cb7aa944",
         "platform": {
            "architecture": "arm64",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 1368,
         "digest": "sha256:9931eb4f416a94ae8d1cc9f501d06c23a9ec836e7df0b708cf95fc686f3a065c",
         "platform": {
            "architecture": "ppc64le",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 1368,
         "digest": "sha256:07a1bb3e16af6345b4985cf3c3d5ee77f899a725c8daba56ba884c1afeafd038",
         "platform": {
            "architecture": "s390x",
            "os": "linux"
         }
      }
   ]
}
```

### CODE REVIEW

**Comment by rsafonseca** [comment]
Looks like all tests are now passing, can you add a LGTM label here @Random-Liu ? Right now the lack of arm64 image is the only blocker on my environment to have all our daemonsets working on ARM64 nodes :)

**Comment by manelpb** [comment]
+1 for this

**Comment by jkroepke** [comment]
@Random-Liu @xinydev 

Hi Guy, can I help here to finish this PR? In case you are busy, are you able to ping colleagues?

**Comment by xinydev** [comment]
> @Random-Liu @xinydev
> 
> Hi Guy, can I help here to finish this PR? In case you are busy, are you able to ping colleagues?

@jkroepke  There is a new PR(https://github.com/kubernetes/node-problem-detector/pull/634) that fixes a bug with the current PR, you can take a look at that.  I am going to close this one.

**Pull request closed without merging**
