### PR TITLE
Replace boskos client with the one in sigs.k8s.io/boskos

### PR DESCRIPTION
**Pull request by MartinForReal**
Replace boskos client with the one in sigs.k8s.io/boskos so that k8s.io/test-infra can be removed. 
Part of #771

### CODE REVIEW

**Comment by MartinForReal** [comment]
@vteratipally I've rebased the pr. Could you please take a look? Thanks!

**Comment by MartinForReal** [comment]
<html>
<body>


/test pull-npd-build
--


<br class="Apple-interchange-newline">
</body>
</html>

**Comment by mmiranda96** [comment]
Test issue has been fixed.
/retest

**Comment by MartinForReal** [comment]
@mmiranda96 Could you please approve the pr? Thanks!

**Review by vteratipally — APPROVED** [review]

**Pull request merged**
