### PR TITLE
[WIP] Add k8s_container exporter

### PR DESCRIPTION
**Pull request by karan**

### CODE REVIEW

**Comment by karan** [comment]
.hold

**Comment by wangzhen127** [comment]
Is this PR a copy of https://github.com/kubernetes/node-problem-detector/tree/master/pkg/exporters/stackdriver? If so, please mention it in the description.

**Comment by karan** [comment]
Right - it's based on that with modifications (and ack - I'll add a link back to the existing one). This PR is not ready for review yet. I'll remove the hold once it is.

**Pull request closed without merging**
