### PR TITLE
Add ABRT adaptor config

### PR DESCRIPTION
**Pull request by juliusmilan**
This config allows NPD to catch problems detected by ABRT, ABRT can find various problems (see the link) and log them to journalctl in format described here:
https://github.com/abrt/abrt/wiki/systemd-journal-catalog-messages

Work sequence:
1. ABRT processes problem and logs to journal
2. NDP catches ABRT logs and report them to upper layer

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/node-problem-detector/105)

### CODE REVIEW

**Comment by Random-Liu** [comment]
@juliusmilan This is cool! Have you verified this config?

@dchen1107

**Comment by juliusmilan** [comment]
@Random-Liu Thank you, yes verified for all kinds of ABRT messages present in config.

**Comment by Random-Liu** [comment]
LGTM.

@juliusmilan So you run NPD in Kubernetes cluster and did see node events generated, right?

**Comment by Random-Liu** [comment]
Will merge after your confirmation. :)

**Comment by dchen1107** [comment]
Thanks for the pr to extend the usability of NPD.

**Comment by juliusmilan** [comment]
@Random-Liu I tested it using netcat in following manner:
started netcat on localhost:
$ nc -l -k 127.0.0.1 5000
then I created a crash using will_python_raise, will_abort, ... (from package will_crash - simple testing programs, each just crashes somehow) to be catched by ABRT:
$ will_python_raise
after this in journalctl appeared following line, then I executed NPD
abrt-notification[24992]: Process 24711 (will_python_raise) of user 1000 encountered an uncaught ZeroDivisionError exception
$ ./bin/node-problem-detector --apiserver-override=http://127.0.0.1:5000?inClusterConfig=false --system-log-monitors=config/abrt-adaptor.json

following is what catched my netcat (so I knew config works well):

POST /api/v1/namespaces/default/events HTTP/1.1
Host: 127.0.0.1:5000
User-Agent: node-problem-detector/v1.4.0 (linux/amd64) kubernetes/$Format
Content-Length: 572
Accept: application/json, */*
Content-Type: application/json
Accept-Encoding: gzip

{"kind":"Event","apiVersion":"v1","metadata":{"name":"dhcp-24-175.brq.redhat.com.14aff755624bb494","namespace":"default","creationTimestamp":null},"involvedObject":{"kind":"Node","name":"dhcp-24-175.brq.redhat.com","uid":"dhcp-24-175.brq.redhat.com"},"reason":"UncaughtException","message":"Process 24711 (will_python_raise) of user 1000 encountered an uncaught ZeroDivisionError exception","source":{"component":"abrt-adaptor","host":"dhcp-24-175.brq.redhat.com"},"firstTimestamp":"2017-03-28T06:19:07Z","lastTimestamp":"2017-03-28T06:19:07Z","count":1,"type":"Warning"}
PATCH /api/v1/nodes/dhcp-24-175.brq.redhat.com/status HTTP/1.1
Host: 127.0.0.1:5000
User-Agent: node-problem-detector/v1.4.0 (linux/amd64) kubernetes/$Format
Content-Length: 28
Accept: application/json, */*
Content-Type: application/strategic-merge-patch+json
Accept-Encoding: gzip

{"status":{"conditions":[]}}

I did similar test for all kinds of problems I added to the config/abrt-adaptor.json

**Comment by Random-Liu** [comment]
Cool~ LGTM

**Comment by Random-Liu** [comment]
@juliusmilan Merged! Thanks for the improvement!

**Pull request merged**
