### PR TITLE
Add jeremyje as a reviewer.

### PR DESCRIPTION
**Pull request by jeremyje**
I'd like to self nominate myself as a reviewer (not approver) for NPD. I can review Windows enhancements that are tracked by https://github.com/kubernetes/node-problem-detector/issues/461 and if necessary take up reviews for NPD in general.

### CODE REVIEW

**Comment by Random-Liu** [comment]
Could you please provide proof for https://github.com/kubernetes/community/blob/4026287dc3a2d16762353b62ca2fe4b80682960a/community-membership.md#reviewer in the commit message? Thanks!

**Comment by jeremyje** [comment]
* member for at least 3 months
  * Joined Kubernetes in December 4, 2020, https://github.com/kubernetes/org/pull/2366 via https://github.com/kubernetes/org/issues/2352.
* Primary reviewer for at least 5 PRs to the codebase
  * Reviewed 3 PRs: https://github.com/kubernetes/node-problem-detector/pulls?q=reviewed-by%3Ajeremyje+is%3Aclosed+is%3Apr+-author%3Ajeremyje+
* Reviewed or merged at least 20 substantial PRs to the codebase
  * I have submitted 9 PRs: https://github.com/kubernetes/node-problem-detector/pulls?q=is%3Apr+author%3Ajeremyje+is%3Aclosed
  * 1 PR is pending.
  * So up to 12 here.
* Knowledgeable about the codebase
  * Yes, I've written a design and made initial changes to introduce Windows support. https://github.com/kubernetes/node-problem-detector/issues/461
* Sponsored by a subproject approver
  * Requesting @Random-Liu 
* With no objections from other approvers
* Done through PR to update the OWNERS file
  * This change
* May either self-nominate, be nominated by an approver in this subproject, or be nominated by a robot
  * Self nominating

**Pull request closed without merging**
