### PR TITLE
Fix the dockerfile to use the right binary.

### PR DESCRIPTION
**Pull request by Random-Liu**
@andyxning Could you help me review this?

I found we missed the Dockerfile in https://github.com/kubernetes/node-problem-detector/pull/54.

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/node-problem-detector/56)

### CODE REVIEW

**Comment by Random-Liu** [comment]
Hm, I can't add you as reviewer. I'll figure out how to do that. :)

**Comment by Random-Liu** [comment]
@andyxning Hm, ok. Only people in Kubernetes organization could be assigned as Reviewer. Could you still help me review this PR?

**Comment by andyxning** [comment]
SGTM

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/node-problem-detector/56#-:-KZZQwXOrGIEI8e38v_w:bb73djm)*

**Comment by andyxning** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/node-problem-detector/56)*

**Comment by Random-Liu** [comment]
Apply LGTM based on https://github.com/kubernetes/node-problem-detector/pull/56#issuecomment-268705216.

**Pull request merged**
