### PR TITLE
bump kubernetes version to v1.4.0-beta.3

### PR DESCRIPTION
**Pull request by andyxning**
bump kubernetes version to v1.4.0-beta.3. This is partially a former PR for #49 .

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/node-problem-detector/52)

### CODE REVIEW

**Comment by andyxning** [comment]
@Random-Liu PTAL.

**Comment by andyxning** [comment]
@Random-Liu Please take a look at this PR. This is the part to update kubernetes version.

**Comment by Random-Liu** [comment]
I fetched your PR to my local environment, and found some unused packages.
```
#	deleted:    vendor/bitbucket.org/ww/goautoneg/Makefile
#	deleted:    vendor/bitbucket.org/ww/goautoneg/README.txt
#	deleted:    vendor/bitbucket.org/ww/goautoneg/autoneg.go
#	deleted:    vendor/github.com/beorn7/perks/quantile/exampledata.txt
#	deleted:    vendor/github.com/beorn7/perks/quantile/stream.go
#	deleted:    vendor/github.com/docker/docker/LICENSE
#	deleted:    vendor/github.com/docker/docker/NOTICE
#	deleted:    vendor/github.com/docker/docker/pkg/mount/flags.go
#	deleted:    vendor/github.com/docker/docker/pkg/mount/flags_freebsd.go
#	deleted:    vendor/github.com/docker/docker/pkg/mount/flags_linux.go
#	deleted:    vendor/github.com/docker/docker/pkg/mount/flags_unsupported.go
#	deleted:    vendor/github.com/docker/docker/pkg/mount/mount.go
#	deleted:    vendor/github.com/docker/docker/pkg/mount/mounter_freebsd.go
#	deleted:    vendor/github.com/docker/docker/pkg/mount/mounter_linux.go
#	deleted:    vendor/github.com/docker/docker/pkg/mount/mounter_unsupported.go
#	deleted:    vendor/github.com/docker/docker/pkg/mount/mountinfo.go
#	deleted:    vendor/github.com/docker/docker/pkg/mount/mountinfo_freebsd.go
#	deleted:    vendor/github.com/docker/docker/pkg/mount/mountinfo_linux.go
#	deleted:    vendor/github.com/docker/docker/pkg/mount/mountinfo_unsupported.go
#	deleted:    vendor/github.com/docker/docker/pkg/mount/sharedsubtree_linux.go
#	deleted:    vendor/github.com/docker/go-units/CONTRIBUTING.md
#	deleted:    vendor/github.com/docker/go-units/LICENSE.code
#	deleted:    vendor/github.com/docker/go-units/LICENSE.docs
#	deleted:    vendor/github.com/docker/go-units/MAINTAINERS
#	deleted:    vendor/github.com/docker/go-units/README.md
#	deleted:    vendor/github.com/docker/go-units/circle.yml
#	deleted:    vendor/github.com/docker/go-units/duration.go
#	deleted:    vendor/github.com/docker/go-units/size.go
#	deleted:    vendor/github.com/docker/go-units/ulimit.go
#	deleted:    vendor/github.com/golang/protobuf/LICENSE
#	deleted:    vendor/github.com/golang/protobuf/proto/Makefile
#	deleted:    vendor/github.com/golang/protobuf/proto/clone.go
#	deleted:    vendor/github.com/golang/protobuf/proto/decode.go
#	deleted:    vendor/github.com/golang/protobuf/proto/encode.go
#	deleted:    vendor/github.com/golang/protobuf/proto/equal.go
#	deleted:    vendor/github.com/golang/protobuf/proto/extensions.go
#	deleted:    vendor/github.com/golang/protobuf/proto/lib.go
#	deleted:    vendor/github.com/golang/protobuf/proto/message_set.go
#	deleted:    vendor/github.com/golang/protobuf/proto/pointer_reflect.go
#	deleted:    vendor/github.com/golang/protobuf/proto/pointer_unsafe.go
#	deleted:    vendor/github.com/golang/protobuf/proto/properties.go
#	deleted:    vendor/github.com/golang/protobuf/proto/text.go
#	deleted:    vendor/github.com/golang/protobuf/proto/text_parser.go
#	deleted:    vendor/github.com/matttproud/golang_protobuf_extensions/LICENSE
#	deleted:    vendor/github.com/matttproud/golang_protobuf_extensions/pbutil/decode.go
#	deleted:    vendor/github.com/matttproud/golang_protobuf_extensions/pbutil/doc.go
#	deleted:    vendor/github.com/matttproud/golang_protobuf_extensions/pbutil/encode.go
#	deleted:    vendor/github.com/opencontainers/runc/LICENSE
#	deleted:    vendor/github.com/opencontainers/runc/NOTICE
#	deleted:    vendor/github.com/opencontainers/runc/libcontainer/cgroups/cgroups.go
#	deleted:    vendor/github.com/opencontainers/runc/libcontainer/cgroups/cgroups_unsupported.go
#	deleted:    vendor/github.com/opencontainers/runc/libcontainer/cgroups/fs/apply_raw.go
#	deleted:    vendor/github.com/opencontainers/runc/libcontainer/cgroups/fs/blkio.go
#	deleted:    vendor/github.com/opencontainers/runc/libcontainer/cgroups/fs/cpu.go
#	deleted:    vendor/github.com/opencontainers/runc/libcontainer/cgroups/fs/cpuacct.go
#	deleted:    vendor/github.com/opencontainers/runc/libcontainer/cgroups/fs/cpuset.go
#	deleted:    vendor/github.com/opencontainers/runc/libcontainer/cgroups/fs/devices.go
#	deleted:    vendor/github.com/opencontainers/runc/libcontainer/cgroups/fs/freezer.go
#	deleted:    vendor/github.com/opencontainers/runc/libcontainer/cgroups/fs/fs_unsupported.go
#	deleted:    vendor/github.com/opencontainers/runc/libcontainer/cgroups/fs/hugetlb.go
#	deleted:    vendor/github.com/opencontainers/runc/libcontainer/cgroups/fs/memory.go
#	deleted:    vendor/github.com/opencontainers/runc/libcontainer/cgroups/fs/name.go
#	deleted:    vendor/github.com/opencontainers/runc/libcontainer/cgroups/fs/net_cls.go
#	deleted:    vendor/github.com/opencontainers/runc/libcontainer/cgroups/fs/net_prio.go
#	deleted:    vendor/github.com/opencontainers/runc/libcontainer/cgroups/fs/perf_event.go
#	deleted:    vendor/github.com/opencontainers/runc/libcontainer/cgroups/fs/pids.go
#	deleted:    vendor/github.com/opencontainers/runc/libcontainer/cgroups/fs/utils.go
#	deleted:    vendor/github.com/opencontainers/runc/libcontainer/cgroups/stats.go
#	deleted:    vendor/github.com/opencontainers/runc/libcontainer/cgroups/utils.go
#	deleted:    vendor/github.com/opencontainers/runc/libcontainer/configs/blkio_device.go
#	deleted:    vendor/github.com/opencontainers/runc/libcontainer/configs/cgroup_unix.go
#	deleted:    vendor/github.com/opencontainers/runc/libcontainer/configs/cgroup_unsupported.go
#	deleted:    vendor/github.com/opencontainers/runc/libcontainer/configs/cgroup_windows.go
#	deleted:    vendor/github.com/opencontainers/runc/libcontainer/configs/config.go
#	deleted:    vendor/github.com/opencontainers/runc/libcontainer/configs/config_unix.go
#	deleted:    vendor/github.com/opencontainers/runc/libcontainer/configs/device.go
#	deleted:    vendor/github.com/opencontainers/runc/libcontainer/configs/device_defaults.go
#	deleted:    vendor/github.com/opencontainers/runc/libcontainer/configs/hugepage_limit.go
#	deleted:    vendor/github.com/opencontainers/runc/libcontainer/configs/interface_priority_map.go
#	deleted:    vendor/github.com/opencontainers/runc/libcontainer/configs/mount.go
#	deleted:    vendor/github.com/opencontainers/runc/libcontainer/configs/namespaces.go
#	deleted:    vendor/github.com/opencontainers/runc/libcontainer/configs/namespaces_syscall.go
#	deleted:    vendor/github.com/opencontainers/runc/libcontainer/configs/namespaces_syscall_unsupported.go
#	deleted:    vendor/github.com/opencontainers/runc/libcontainer/configs/namespaces_unix.go
#	deleted:    vendor/github.com/opencontainers/runc/libcontainer/configs/namespaces_unsupported.go
#	deleted:    vendor/github.com/opencontainers/runc/libcontainer/configs/network.go
#	deleted:    vendor/github.com/opencontainers/runc/libcontainer/system/linux.go
#	deleted:    vendor/github.com/opencontainers/runc/libcontainer/system/proc.go
#	deleted:    vendor/github.com/opencontainers/runc/libcontainer/system/setns_linux.go
#	deleted:    vendor/github.com/opencontainers/runc/libcontainer/system/syscall_linux_386.go
#	deleted:    vendor/github.com/opencontainers/runc/libcontainer/system/syscall_linux_64.go
#	deleted:    vendor/github.com/opencontainers/runc/libcontainer/system/syscall_linux_arm.go
#	deleted:    vendor/github.com/opencontainers/runc/libcontainer/system/sysconfig.go
#	deleted:    vendor/github.com/opencontainers/runc/libcontainer/system/sysconfig_notcgo.go
#	deleted:    vendor/github.com/opencontainers/runc/libcontainer/system/xattrs_linux.go
#	deleted:    vendor/github.com/prometheus/client_golang/LICENSE
#	deleted:    vendor/github.com/prometheus/client_golang/NOTICE
#	deleted:    vendor/github.com/prometheus/client_golang/prometheus/.gitignore
#	deleted:    vendor/github.com/prometheus/client_golang/prometheus/README.md
#	deleted:    vendor/github.com/prometheus/client_golang/prometheus/collector.go
#	deleted:    vendor/github.com/prometheus/client_golang/prometheus/counter.go
#	deleted:    vendor/github.com/prometheus/client_golang/prometheus/desc.go
#	deleted:    vendor/github.com/prometheus/client_golang/prometheus/doc.go
#	deleted:    vendor/github.com/prometheus/client_golang/prometheus/expvar.go
#	deleted:    vendor/github.com/prometheus/client_golang/prometheus/gauge.go
#	deleted:    vendor/github.com/prometheus/client_golang/prometheus/go_collector.go
#	deleted:    vendor/github.com/prometheus/client_golang/prometheus/histogram.go
#	deleted:    vendor/github.com/prometheus/client_golang/prometheus/http.go
#	deleted:    vendor/github.com/prometheus/client_golang/prometheus/metric.go
#	deleted:    vendor/github.com/prometheus/client_golang/prometheus/process_collector.go
#	deleted:    vendor/github.com/prometheus/client_golang/prometheus/push.go
#	deleted:    vendor/github.com/prometheus/client_golang/prometheus/registry.go
#	deleted:    vendor/github.com/prometheus/client_golang/prometheus/summary.go
#	deleted:    vendor/github.com/prometheus/client_golang/prometheus/untyped.go
#	deleted:    vendor/github.com/prometheus/client_golang/prometheus/value.go
#	deleted:    vendor/github.com/prometheus/client_golang/prometheus/vec.go
#	deleted:    vendor/github.com/prometheus/client_model/LICENSE
#	deleted:    vendor/github.com/prometheus/client_model/NOTICE
#	deleted:    vendor/github.com/prometheus/client_model/go/metrics.pb.go
#	deleted:    vendor/github.com/prometheus/common/expfmt/decode.go
#	deleted:    vendor/github.com/prometheus/common/expfmt/encode.go
#	deleted:    vendor/github.com/prometheus/common/expfmt/expfmt.go
#	deleted:    vendor/github.com/prometheus/common/expfmt/fuzz.go
#	deleted:    vendor/github.com/prometheus/common/expfmt/json_decode.go
#	deleted:    vendor/github.com/prometheus/common/expfmt/text_create.go
#	deleted:    vendor/github.com/prometheus/common/expfmt/text_parse.go
#	deleted:    vendor/github.com/prometheus/common/model/fingerprinting.go
#	deleted:    vendor/github.com/prometheus/common/model/labels.go
#	deleted:    vendor/github.com/prometheus/common/model/labelset.go
#	deleted:    vendor/github.com/prometheus/common/model/metric.go
#	deleted:    vendor/github.com/prometheus/common/model/model.go
#	deleted:    vendor/github.com/prometheus/common/model/signature.go
#	deleted:    vendor/github.com/prometheus/common/model/time.go
#	deleted:    vendor/github.com/prometheus/common/model/value.go
#	deleted:    vendor/github.com/prometheus/procfs/.travis.yml
#	deleted:    vendor/github.com/prometheus/procfs/AUTHORS.md
#	deleted:    vendor/github.com/prometheus/procfs/CONTRIBUTING.md
#	deleted:    vendor/github.com/prometheus/procfs/LICENSE
#	deleted:    vendor/github.com/prometheus/procfs/NOTICE
#	deleted:    vendor/github.com/prometheus/procfs/README.md
#	deleted:    vendor/github.com/prometheus/procfs/doc.go
#	deleted:    vendor/github.com/prometheus/procfs/fs.go
#	deleted:    vendor/github.com/prometheus/procfs/proc.go
#	deleted:    vendor/github.com/prometheus/procfs/proc_limits.go
#	deleted:    vendor/github.com/prometheus/procfs/proc_stat.go
#	deleted:    vendor/github.com/prometheus/procfs/stat.go
```

How did you update the Godep?

**Comment by andyxning** [comment]
@Random-Liu It consumes me about almost six hours to make all the PR green. However, something is still wrong. 

I will update this later. Hard work recently. :)

**Comment by Random-Liu** [comment]
> @Random-Liu It consumes me about almost six hours to make the PR green. However, something is still wrong. :(

Yeah, in K8s, it sometimes takes us 2 days to update Godep dependency... It's really confusing. I think we are going to switch to another dependency management tool.

Currently the Godep of the repo is in a bad condition. It should have been fixed in https://github.com/kubernetes/node-problem-detector/pull/39, but I believe it still needs some time to get #39 merged.

I'll send a PR to fix the current Godep to make it easier for you to update kubernetes dependency.

**Comment by andyxning** [comment]
@Random-Liu I have updated the PR. It should be ok now. PTAL.

**Comment by andyxning** [comment]
BTW, imo, it may make npd complicated by linking cgo for supporting systemd.

**Comment by Random-Liu** [comment]
@andyxning That's why I added a option to disable journald support in #39.

**Comment by andyxning** [comment]
@Random-Liu [FYI](https://github.com/tools/godep/issues/478)

**Comment by Random-Liu** [comment]
@andyxning I used similar way. However, IIUC, cadvisor and npd is using different version of go-systemd, which will confuse Godep. I have to run `godep save` twice to include `vendor/github.com/coreos/go-systemd/journal/journal.go`.

How did you solve this?

**Comment by andyxning** [comment]
@Random-Liu I did not encounter that problem. 

However, when i run `godep save ./...` after `godep resotre -v`. The `golang.org/x/net/idna` package is lost and the first updated PR is not passed. 

After that, i run `godep update golang.org/x/net/...` and `golang.org/x/net/idna` has been added. 

I am also curious about Godep. Not knowing why it works and why it does not work. :(

**Comment by Random-Liu** [comment]
Hm, ok. It's mystery. :(

I'll validate your PR. Once it works, I'll approve this PR and review https://github.com/kubernetes/node-problem-detector/pull/49.

**Comment by andyxning** [comment]
@Random-Liu ok. Once this PR is accepted, i will rebase #49

**Comment by Random-Liu** [comment]
@andyxning I checked your PR, and after I run:
```
godep restore
rm -rf Godep/ vendor/
godep save ./...
```
I found that `golang.org/x/net/idna` is still missing.
```
#	deleted:    vendor/golang.org/x/net/idna/idna.go
#	deleted:    vendor/golang.org/x/net/idna/punycode.go
```
I have to run `godep save ./...` twice or run `godep update golang.org/x/net/...` to include it.

The reason is that `k8s.io/kubernetes` and `k8s.io/client-go` is using a different `golang.org/x/net` version with npd. That version doesn't have `idna` package.

The fix is:
```
godep restore
cd ../../golang.org/x/net
git checkout e90d6d0afc4c315a0d87a568ae68577cc15149a0 # The version kubernetes and client-go is using
cd -
rm -rf Godep/ vendor/
godep save ./...
```
This kind of Godep problem has happened many times to us. It's really annoying. (See https://github.com/kubernetes/node-problem-detector/issues/7)

**Comment by andyxning** [comment]
> The reason is that k8s.io/kubernetes and k8s.io/client-go is using a different golang.org/x/net version with npd. That version doesn't have idna package.

Now idna is not a dependency anymore. 👏  Thanks @Random-Liu 
`godep restore` and `godep save ./...` now produce stable and correct result. 

> Another question is that it seems that heapster switched to kubernetes 1.5 from 1.4.0-beta.3. I'm fine with using 1.4 for now, but we should update to 1.5 later. :)

Heapster bump to Kubernetes 1.5 for next release 1.3.0. They have the following corresponding relations

|Heapster|Kubernetes|
|-|-|
|1.1.0|1.3.0|
|1.2.0|1.4.0|
|1.3.0|1.5.0| 

I also think npd should also be released like this. 
|Heapster|Kubernetes|
|-|-|
|v0.1|1.3.0|
|v0.2|1.4.0|
|v0.3|1.5.0|

WDYT. 
I agree that we should bump to kubernetes version to 1.5.0 only after heapster 1.3.0 is released.

**Comment by Random-Liu** [comment]
@andyxning Thanks for your suggestion. I'll reference projects like cadvisor, heapster and kubedns and write a simple doc for npd release process. It should be similar with your suggestion.

**Comment by Random-Liu** [comment]
LGTM.

**Pull request merged**
