### PR TITLE
Test using "k8s-infra-e2e-boskos-157"

### PR DESCRIPTION
**Pull request by hakman**
Ref: #970

### CODE REVIEW

**Comment by ameukam** [comment]
I'm away from OSS laptop currently.
I'll take a look later.

**Comment by hakman** [comment]
> I'm away from OSS laptop currently. I'll take a look later.

No rush, just wanted to make it easy to find.

**Comment by hakman** [comment]
Thanks @ameukam. Seems it's not related to infra, but maybe to COS or the linux kernel. See https://github.com/kubernetes/node-problem-detector/issues/970#issuecomment-2409105964.
/close

**Pull request closed without merging**
