### PR TITLE
updated the custom plugin configuration doc

### PR DESCRIPTION
**Pull request by xmcqueen**
Documentation-only chnge:

Updated the custom plugin doc to clarify the usage for reason and message. I have been noticing people don't know how to use reason, and message, and often have a hard time making sense of the Conditions.

### CODE REVIEW

**Comment by xmcqueen** [comment]
There's a problem pulling the *cos-89-lts* image:

```
Unable to get image from family cos-89-lts at project cos-cloud: googleapi: Error 404: The resource 'projects/cos-cloud/global/images/family/cos-89-lts' was not found, notFound
```

**Comment by xmcqueen** [comment]
Maybe this should be `cos-stable`?

**Comment by mmiranda96** [comment]
Thanks for this doc update!
/lgtm

**Comment by MartinForReal** [comment]
<html>
<body>


/test pull-npd-e2e-node
--


<br class="Apple-interchange-newline">
</body>
</html>

**Pull request merged**
