### PR TITLE
Move glog/klog logging to klog/v2

### PR DESCRIPTION
**Pull request by mrueg**
Unify logging and use the most recent one that is used within the k8s project.

### CODE REVIEW

**Comment by hakman** [comment]
This should be a very nice addition.
/test pull-npd-e2e-test

**Comment by mrueg** [comment]
@vteratipally I need to figure out what's not right before we can merge it. The tests never run successful.

**Comment by vteratipally** [comment]
pull-npd-e2e-node is failing because the master node is not up.

pull-npd-e2e-test - taking a look

**Comment by vteratipally** [comment]
/close

closing the PR as this is addressed in another

**Pull request closed without merging**
