### PR TITLE
Fixing minor bug in kernel monitor filepath

### LINKED ISSUE #60: Bump the version to v0.3 in makefile, manifest and readme
After adding the standalone mode in #49 , I created and pushed a new docker image gcr.io/google_containers/node-problem-detector:v0.3 which includes these changes for use by [kubemark](https://github.com/kubernetes/kubernetes/tree/master/test/kubemark). However this version bump has to be reflected in:
1. version tag inside the Makefile
2. image inside the node-problem-detector.yaml
3. readme, to indicate that v0.3 is the latest version and/or suggested for use?

@Random-Liu Hope this push doesn't disturb any plans you might be having for npd release schedule. If yes, it's not difficult to revert this change, as I just did it for use in kubemark.

### LINKED ISSUE #62: Kernel monitor file is wrongly named in node-problem-detector.go
The default path to the kernel monitor config in [node-problem-detector.go](https://github.com/kubernetes/node-problem-detector/blob/master/node_problem_detector.go#L30) is '/config/kernel_monitor.json'. However, the file in the config/ directory of the repo is named 'kernel-monitor.json' (hyphen at one place and underscore at the other). They need to be named the same.

cc @Random-Liu

### PR DESCRIPTION
**Pull request by shyamjvs**
Fixes #62 (kernel monitor filepath change)
Ref #60 (bumping version to v0.3)

@Random-Liu Can you PTAL?

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/node-problem-detector/63)

### CODE REVIEW

**Comment by Random-Liu** [comment]
Could we fix the config path in this PR, but not bumping up the version?

I prefer to bump up the version after the release process is defined. I'll try to write it up soon. :)

**Comment by shyamjvs** [comment]
Yes we can do that. But given that the code has already changed, and the version in the Makefile hasn't bumped up, it's kind of urgent to do it as there is a risk for someone to accidentally rewrite the v0.2 image with a new one. Need to prevent such a thing happening. What do you say?

**Comment by Random-Liu** [comment]
Cause pushing image to gcr needs special permission. It should be fine to leave it v0.2.

I'll try to finish the release process soon, and let's bump up the version then. :)
Maybe we'll change the version to v0.3-alpha, v0.3.0 or something else.

**Comment by shyamjvs** [comment]
Sounds good. Changed the PR.

**Comment by Random-Liu** [comment]
LGTM

**Comment by andyxning** [comment]
@Random-Liu @shyamjvs I prefer to use v0.2.x version number for now. After we solved all the related P0 problems referred  in #58, we can bump minor version to 0.3.x. This is still make a chance for node-problem-detector to keep pace in Kubernetes.

**Comment by andyxning** [comment]
@Random-Liu @shyamjvs I prefer to use 0.2.x version number for now. After we solve all the pending  P0 prolbems in #58 , we can bump version to 0.3.x and keep in sync with Kubernetes release schedule.

This is just a recommendation. :)

**Comment by Random-Liu** [comment]
@andyxning As you said, we should:
1) For new release (0.3.0), we should:
  a) Release 0.3.0 before Kubernetes 1.6 code freeze.
  b) Bump up the NPD version in kubernetes NPD e2e test.
  c) Bump up the NPD version in kubernetes cluster after the e2e test stabilizes.
2) For patch release (this case), we should:
  a) Merge the fix into HEAD.
  b) Cherrypick the fix into 0.2 branch (I didn't create one which I should)
  c) Release 0.2.x image as you said.

**Comment by Random-Liu** [comment]
@andyxning @shyamjvs Hm, I'm really too busy to finish the doc.
The priority of the release instruction doc is relatively low, and I think the version control will be pretty much similar with https://github.com/kubernetes/node-problem-detector/pull/63#issuecomment-271804778.

I'll file an issue and finish the doc after we release 0.3.0.

**Pull request merged**
