### PR TITLE
bump k8s.io to 1.24.15 and replace boskos client

### PR DESCRIPTION
**Pull request by MartinForReal**
add context. Context 
replace boskos client in test-infra with sigs.k8s.io/boskos
bump k8s.io to 1.24.15

### CODE REVIEW

**Comment by MartinForReal** [comment]
related: #761

**Comment by vteratipally** [comment]
> add context. Context
Any specific reason for splitting the context

**Comment by MartinForReal** [comment]
because context is required in new k8s client

**Comment by mmiranda96** [comment]
Can we split this PR into 2 or more? Adding context can be done before upgrading dependencies. And I think we can do the same with the Boskos client (correct me if I'm wrong on this one).

**Comment by vteratipally** [comment]
> Can we split this PR into 2 or more? Adding context can be done before upgrading dependencies. And I think we can do the same with the Boskos client (correct me if I'm wrong on this one).

Yes,  I agree with Mike. It will be clear if we split the PR in two parts.

**Comment by MartinForReal** [comment]
I've opened two pr. And I will bump the dependencies after these two pr has been merged. 
Could you please take a look? Thanks! @mmiranda96 @vteratipally

**Pull request closed without merging**
