### PR TITLE
Install system lib in build.sh

### PR DESCRIPTION
**Pull request by wangzhen127**
Install journald system lib in build.sh

Part of https://github.com/kubernetes/node-problem-detector/issues/236.

### CODE REVIEW

**Comment by wangzhen127** [comment]
The build error shows:
```
cmd/node_problem_detector.go:29:2: cannot find package "k8s.io/node-problem-detector/cmd/options" in any of:
/home/prow/go/src/github.com/kubernetes/node-problem-detector/vendor/k8s.io/node-problem-detector/cmd/options (vendor tree)
/usr/local/go/src/k8s.io/node-problem-detector/cmd/options (from $GOROOT)
/home/prow/go/src/k8s.io/node-problem-detector/cmd/options (from $GOPATH)
```

It seems that node-problem-detector is put under "/home/prow/go/src/**github.com/kubernetes**/node-problem-detector/". But I think it should be "/home/prow/go/src/**k8s.io**/node-problem-detector/.

@krzyzacy, do I need to change anything on test-infra side?

**Comment by wangzhen127** [comment]
Oh, I guess I missed `path_alias`?

**Comment by krzyzacy** [comment]
Oh you are doing docker builds... then you need to enable dind explicitly, like https://github.com/kubernetes/test-infra/blob/66076b42b9dd576afcbb90d6c262b43bcd500034/config/jobs/kubernetes/sig-release/kubernetes-builds.yaml#L7

and https://github.com/kubernetes/test-infra/blob/66076b42b9dd576afcbb90d6c262b43bcd500034/config/jobs/kubernetes/sig-release/kubernetes-builds.yaml#L22-L24

**Comment by krzyzacy** [comment]
```
Run: ('kubetest', '--dump=/logs/artifacts', '--gcp-service-account=/etc/service-account/service-account.json', '--up', '--down', '--test', '--cluster=bootstrap-e2e', '--gcp-network=bootstrap-e2e')
2019/03/14 18:10:26 process.go:96: Saved XML output to /logs/artifacts/junit_runner.xml.
2019/03/14 18:10:26 main.go:307: Something went wrong: called from invalid working directory: must run from kubernetes directory root: /home/prow/go/src/k8s.io/node-problem-detector
```

you need an `--extract=foo` flag

**Comment by krzyzacy** [comment]
s/`ci-latest`/`cl/latest`

**Comment by krzyzacy** [comment]
lol - I think you might want to quote the entire string?

**Pull request merged**
