### PR TITLE
Support multiple reasons per condition for CustomPluginMonitor

### PR DESCRIPTION
**Pull request by jason1028kr**
Issue: https://github.com/kubernetes/node-problem-detector/issues/664

Original issue that describes current behavior: https://github.com/kubernetes/node-problem-detector/issues/566

- plugin uses `intervalEndChan` to signal interval end (all plugins ran for the interval).
- `custom_plugin_monitor.go`'s `monitorLoop()` function now gathers result until it receives interval end signal. Only then, it calls new `generateStatus(results []cpmtypes.Result)` to create one event for each condition.
- unit test added

- local testing output on a test cluster below
## New behaviors:

Node describe output:
```
  Normal  TestIsIntentionallyFailing  6s (x57 over 56m)     test-custom-plugin-monitor  Node condition TestConditionHasProblem is now: True, reason: TestIsIntentionallyFailing
```

NPD pod logs:
```
I0407 00:18:53.174047       1 custom_plugin_monitor.go:361] Initialize condition generated: [{Type:TestConditionHasProblem Status:False Transition:2022-04-07 00:18:53.174038607 +0000 UTC m=+4.099922893 Reason:TestIsOK Message:test condition is OK}]
I0407 00:19:53.173518       1 custom_plugin_monitor.go:340] New status generated: &{Source:test-custom-plugin-monitor Events:[{Severity:info Timestamp:2022-04-07 00:19:53.075037997 +0000 UTC m=+64.000922383 Reason:TestIsIntentionallyFailing Message:Node condition TestConditionHasProblem is now: True, reason: TestIsIntentionallyFailing}] Conditions:[{Type:TestConditionHasProblem Status:True Transition:2022-04-07 00:19:53.075037997 +0000 UTC m=+64.000922383 Reason:TestIsIntentionallyFailing Message:}]}
I0407 00:20:52.977094       1 custom_plugin_monitor.go:340] New status generated: &{Source:test-custom-plugin-monitor Events:[{Severity:info Timestamp:2022-04-07 00:20:52.977058649 +0000 UTC m=+123.902942935 Reason:TestIsIntentionallyFailing Message:Node condition TestConditionHasProblem is now: True, reason: TestIsIntentionallyFailing}] Conditions:[{Type:TestConditionHasProblem Status:True Transition:2022-04-07 00:19:53.075037997 +0000 UTC m=+64.000922383 Reason:TestIsIntentionallyFailing Message:}]}
I0407 00:21:53.075186       1 custom_plugin_monitor.go:340] New status generated: &{Source:test-custom-plugin-monitor Events:[{Severity:info Timestamp:2022-04-07 00:21:53.075120494 +0000 UTC m=+184.001004780 Reason:TestIsIntentionallyFailing Message:Node condition TestConditionHasProblem is now: True, reason: TestIsIntentionallyFailing}] Conditions:[{Type:TestConditionHasProblem Status:True Transition:2022-04-07 00:19:53.075037997 +0000 UTC m=+64.000922383 Reason:TestIsIntentionallyFailing Message:}]}
I0407 00:22:53.074590       1 custom_plugin_monitor.go:340] New status generated: &{Source:test-custom-plugin-monitor Events:[{Severity:info Timestamp:2022-04-07 00:22:53.074550383 +0000 UTC m=+244.000434769 Reason:TestIsIntentionallyFailing Message:Node condition TestConditionHasProblem is now: True, reason: TestIsIntentionallyFailing}] Conditions:[{Type:TestConditionHasProblem Status:True Transition:2022-04-07 00:19:53.075037997 +0000 UTC m=+64.000922383 Reason:TestIsIntentionallyFailing Message:}]}
```

### CODE REVIEW

**Comment by vteratipally** [comment]
thank you for the PR. Could you please squash all commits into one.

**Comment by jason1028kr** [comment]
> thank you for the PR. Could you please squash all commits into one.

Thank you! I've squashed them to one.

**Comment by jason1028kr** [comment]
@vteratipally Does this look good to go ahead?

**Comment by juan-lee** [comment]
@vteratipally could you have another look please?

**Comment by juan-lee** [comment]
@dchen1107 would you be able to help @jason1028kr with a review on his PR?

**Comment by vteratipally** [comment]
Random-Liu could you please take a look at the pr

**Comment by jason1028kr** [comment]
Hello @Random-Liu! Would you mind taking a look at this pr?

**Pull request closed without merging**
