### PR TITLE
Add namespace option for events

### PR DESCRIPTION
**Pull request by muff1nman**
By default node-problem-detector writes events to the default namespace. This PR adds an option to allow events to be written to a different namespace.

### CODE REVIEW

**Comment by xueweiz** [comment]
Looking at the unit test, seems there is some problem:

```
GO111MODULE=on go list -mod vendor -tags " journald" ./... | \
	grep -v "./vendor/*" | \
	GO111MODULE=on xargs go vet -mod vendor -tags " journald"
# k8s.io/node-problem-detector/pkg/exporters/k8sexporter/problemclient
vet: pkg/exporters/k8sexporter/problemclient/problem_client_test.go:45:33: too few arguments in call to getNodeRef
```

Seems the refactoring is breaking some other code paths. Could you please fix them? Thanks! You can run `make test` to verify whether the problem has been fixed.

**Comment by xueweiz** [comment]
/lgtm
/approve

@muff1nman the patch looks good to me. However, it will only be merged after you signed the Linux Foundation CLA. [Here](https://github.com/kubernetes/node-problem-detector/pull/418#issuecomment-595521407) are the necessary steps.

**Comment by muff1nman** [comment]
I signed it.

**Pull request merged**
