### PR TITLE
chores:Update stage gcr repo in test script

### PR DESCRIPTION
**Pull request by MartinForReal**

### CODE REVIEW

**Comment by mmiranda96** [comment]
I created https://github.com/kubernetes/node-problem-detector/pull/782, but seems the issue persists. I posted my findings in https://github.com/kubernetes/kubernetes/issues/119211#issuecomment-1633366524

**Comment by MartinForReal** [comment]
<html>
<body>


/test pull-npd-e2e-node
--


<br class="Apple-interchange-newline">
</body>
</html>

**Comment by MartinForReal** [comment]
<html>
<body>


/test pull-npd-e2e-node
--


<br class="Apple-interchange-newline">
</body>
</html>

**Comment by mmiranda96** [comment]
Let's close this PR, it's no longer needed.
/close

**Pull request closed without merging**
