### PR TITLE
Add medik8s.io to Remdy Systems section

### PR DESCRIPTION
**Pull request by rgolangh**
I would like to add medik8s.io to the list of suggested remedy systems. Seems like
[Node Health Check](https://github.com/medik8s/node-healthcheck-operator) with [Poison Pill](https://github.com/medik8s/poison-pill) is are a great match with NPD and can really expand the 
the list of use-cases for using remediation.

### CODE REVIEW

**Comment by rgolangh** [comment]
@andyxning  or @wangzhen127 can you please review this?

**Comment by beekhof** [comment]
Anyone? Its a tiny docs change

**Comment by beekhof** [comment]
/remove-lifecycle stale

@vteratipally any chance you could have a look at this small docs change?

**Comment by rgolangh** [comment]
@andrewsykim can you please have a look?

**Comment by vteratipally** [comment]
/ok-to-test
/lgtm

Sorry for the delay in review.

**Pull request merged**
