### PR TITLE
Trim go.mod

### PR DESCRIPTION
**Pull request by xueweiz**
This is done via running `GO111MODULE=on go mod tidy`.

This is for #364 .

### CODE REVIEW

**Comment by grosser** [comment]
that needs to be part of CI or it will just come back ... `GO111MODULE=on go mod tidy && git diff --exit-status`

**Comment by xueweiz** [comment]
Hi @grosser , unfortunately "go mod tidy" always return 0 :)

And also I don't think it's a good idea to do this as part of CI, mainly due to the complicity of the build tags. I commented the reasoning [here](https://github.com/kubernetes/node-problem-detector/issues/364#issuecomment-558809179). Please let me know what you think under #364 . Thanks! :)

**Comment by grosser** [comment]
👍

**Pull request merged**
