### PR TITLE
move to community staging bucket

### PR DESCRIPTION
**Pull request by BenTheElder**
part of #920 

following https://github.com/kubernetes/k8s.io/pull/7007

we also need to make sure jobs are on k8s-infra-prow-builds, will go check in test-infra

### CODE REVIEW

**Comment by BenTheElder** [comment]
need https://github.com/kubernetes/test-infra/pull/33015

**Comment by hakman** [comment]
All green now. Thanks @BenTheElder! 😄

**Comment by wangzhen127** [comment]
/lgtm

Thanks, @BenTheElder!

**Pull request merged**
