### PR TITLE
Move test dependencies to test dir

### PR DESCRIPTION
**Pull request by hakman**

### CODE REVIEW

**Comment by vteratipally** [comment]
please resolve conflicts

**Comment by hakman** [comment]
> please resolve conflicts

Done

**Comment by vteratipally** [comment]
```github.com/Azure/azure-sdk-for-go/services/network/mgmt/2019-06-01/network: /home/prow/go/src/k8s.io/kubernetes/_output/local/.gimme/versions/go1.21.1.linux.amd64/pkg/tool/linux_amd64/compile: signal: killed
!!! [0911 19:09:44] Call tree:
!!! [0911 19:09:44]  1: /home/prow/go/src/k8s.io/kubernetes/hack/lib/golang.sh:788 kube::golang::build_some_binaries(...)
!!! [0911 19:09:44]  2: /home/prow/go/src/k8s.io/kubernetes/hack/lib/golang.sh:947 kube::golang::build_binaries_for_platform(...)
!!! [0911 19:09:44]  3: hack/make-rules/build.sh:27 kube::golang::build_binaries(...)
!!! [0911 19:09:44] Call tree:
!!! [0911 19:09:44]  1: hack/make-rules/build.sh:27 kube::golang::build_binaries(...)
!!! [0911 19:09:44] Call tree:
!!! [0911 19:09:44]  1: hack/make-rules/build.sh:27 kube::golang::build_binaries(...)
```

**Comment by hakman** [comment]
Looks to me that the build / test is killed after 20 min, no idea why. Seemed to happen in other PRs, for no apparent reason.

**Comment by hakman** [comment]
@vteratipally Could you check again please?

**Comment by hakman** [comment]
Thanks @vteratipally

**Pull request merged**
