### PR TITLE
Add rocky linux support to GetOSVersion

### PR DESCRIPTION
**Pull request by sudheernv**
**Issue:** Node Problem Detector fails to come up on rocky linux OS. 

**Error Log:**  Failed to retrieve OS version: Unsupported ID in /etc/os-release: "rocky"

### CODE REVIEW

**Review by mmiranda96 — COMMENTED** [review]
/ok-to-test

Wondering if we should just default to `getDebianVersion` if the OS is not COS.

**Comment by mmiranda96** [comment]
Your new unit test is failing.

**Comment by sudheernv** [comment]
> Your new unit test is failing.

Sorry @mmiranda96.  Yesterday, I inadvertently omitted pushing the commit that contained the correct expected string for the newly introduced test case. Pushed new commit with necessary fix now.

-- expectedOSVersion: "8.5 (Green Obsidian)",
++ expectedOSVersion: "rocky 8.5 (Green Obsidian)",

**Review by vteratipally — APPROVED** [review]
/lgtm

**Pull request merged**
