### PR TITLE
[StepSecurity] Apply security best practices

### PR DESCRIPTION
**Pull request by sozercan**
Hey folks,

This is originally generated by https://app.stepsecurity.io/securerepo and I updated with a few changes
https://github.com/sozercan/node-problem-detector/pull/1

What this PR does:
- Adds dependabot with a weekly cadence with grouping for GHA and k8s deps to bump various dependencies like gomod, docker etc, to make lives of maintainers easier
- introduces codeql, openssf scorecard and dependency review to improve supply chain security
- pins existing GHA to improve security. these dependencies will still automatically get bumped by dependabot
- adds harden runner with an audit policy. this will surface network endpoints used by the CI. and in the future, you can change this to deny to enable network isolation for improved security
- sets least amount of permissions to existing workflows
- adds optional pre-commit hooks to shift left to prevent any cred leaks, linting, etc
- pins golang builder image to a digest. this will still automatically get bumped by dependabot
- remove baseimage docker var, since the image won't be able to get bumped automatically with that

### CODE REVIEW

**Comment by hakman** [comment]
@sozercan This looks amazing. Should make maintaining this repo much easier.
@wangzhen127 Could you please take a look?
/lgtm

**Comment by hakman** [comment]
Ping @wangzhen127 @jingxu97

**Comment by jingxu97** [comment]
sorry for the delay, I think this is good for our use case.

**Pull request merged**
