### PR TITLE
Add two dependencies

### PR DESCRIPTION
**Pull request by xueweiz**
This PR introduced two dependencies:

- `github.com/shirou/gopsutil/host`
- `github.com/cobaugh/osrelease`

They are needed in #303. I separated out the vendor changes, because they are larger while easier to
review.

They are done via:
```
GO111MODULE=on go get github.com/shirou/gopsutil/host
GO111MODULE=on go mod vendor
GO111MODULE=on go get github.com/cobaugh/osrelease
GO111MODULE=on go mod vendor
```

### CODE REVIEW

**Comment by wangzhen127** [comment]
What functions do you plan to use from this library? I am trying to see what is being used by kubernetes community for similar functionalities and check if there is any best practice.

**Comment by xueweiz** [comment]
> What functions do you plan to use from this library?
They haven't been finalized yet. But here is the list of functions I'm experimenting with:

https://godoc.org/github.com/shirou/gopsutil/host#KernelVersion
https://godoc.org/github.com/shirou/gopsutil/host#Uptime

https://godoc.org/github.com/shirou/gopsutil/process#Process.CPUPercent
https://godoc.org/github.com/shirou/gopsutil/process#Process.Connections
https://godoc.org/github.com/shirou/gopsutil/process#Process.CreateTime
https://godoc.org/github.com/shirou/gopsutil/process#Process.IOCounters
https://godoc.org/github.com/shirou/gopsutil/process#Process.MemoryInfo
https://godoc.org/github.com/shirou/gopsutil/process#Process.MemoryPercent
https://godoc.org/github.com/shirou/gopsutil/process#Process.NetIOCounters
https://godoc.org/github.com/shirou/gopsutil/process#Process.NumFDs

Thanks for check with what k8s community has right now! And please let me know if you have any findings :)

**Comment by xueweiz** [comment]
btw this is still the gopsutil library (#289) we used for retrieving disk stats in #275 

The library is composed of a few components (host, process, mem, disk, etc...). I only included disk last time.
Actually, maybe I should just include all of them in the vendor. Because we will probably need them in near future anyways. WDYT?

**Comment by wangzhen127** [comment]
> Actually, maybe I should just include all of them in the vendor. Because we will probably need them in near future anyways. WDYT?

Sounds good to me.

I didn't find any similar usage in k8s. Let's use this for now. We can change to other stuff later if there is any better library.

**Comment by xueweiz** [comment]
> Actually, maybe I should just include all of them in the vendor

Seems this is not very straight forward. When I do `go mod vendor`, it automatically drops all unused modules.

Let's just import what we use right now, and import the new ones when we need them.

**Comment by wangzhen127** [comment]
/hold
Are you going to merge this first and then the other one?

**Comment by xueweiz** [comment]
Yes, I plan to merge this first. Then rebase #303 , then merge #303

**Comment by xueweiz** [comment]
For convenience, let's just submit the vendor changes as part of #303 
I'll drop this PR.

**Pull request closed without merging**
