### PR TITLE
Add arbitray system log support

### PR DESCRIPTION
**Pull request by Random-Liu**
For https://github.com/kubernetes/node-problem-detector/issues/44.

Based on https://github.com/kubernetes/node-problem-detector/pull/81.

This PR:
* Add `PluginConfig` for plugin specific configuration.
* Add `source` in journald plugin configuration to make sdjournal `SYSTEM_IDENTIFIER` configurable.
* Add `timestamp` regular expression, `message` regular expression and `timestampFormat` configuration in syslog plugin configuration. (We plan to change this to be `filelog`, because it can handle not only syslog)

TODOs for this work:
* Add multiple configuration files support. NPD should start a system log monitor for each passed in configurtion, so that it can monitor different services at the same time.
* Rename `syslog` to `filelog`.
* Rename `kernel monitor` to `system log monitor`, change all "kernel" reference in the code.
* Optimize the efficiency to make the system log monitor more light weight.
* Add document for the new behavior.
* Update kubernetes e2e test to test the new behavior.

/cc @dchen1107 @kubernetes/node-problem-detector-reviewers

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/node-problem-detector/88)

### CODE REVIEW

**Comment by Random-Liu** [comment]
I've updated the e2e test locally according the change in this PR, and the PR passed the test.

Will update the e2e test in Kubernetes repo after this PR is merged.

**Comment by dchen1107** [comment]
Can you rebased this one? #81 was merged, and I am reviewing this one today.

**Comment by Random-Liu** [comment]
@dchen1107 Rebased. :)

**Comment by dchen1107** [comment]
LGTM

**Pull request merged**
