### PR TITLE
Generalize the kernel monitor code.

### PR DESCRIPTION
**Pull request by Random-Liu**
For https://github.com/kubernetes/node-problem-detector/issues/44.
Based on https://github.com/kubernetes/node-problem-detector/pull/81 and https://github.com/kubernetes/node-problem-detector/pull/88.

his PR:
* Change kernel monitor to system log monitor, because we want to generalize kernel monitor to detect problems of different system daemons.
* Change `syslog` to `filelog`, because actually it does not only support syslog now, it should be able to support most file based logs.
* Update the README.md.

/cc @dchen1107 @kubernetes/node-problem-detector-reviewers

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/node-problem-detector/92)

### CODE REVIEW

**Comment by dchen1107** [comment]
I reviewed two commits 1) Change kernel specific name in code base and change syslog to filelog
2) Update the README.md in this pr. and they are lgtm. 

Meanwhile, should we update README that node-problem-detector can also run as a standalone daemon now? I am ok with another pr.

**Comment by dchen1107** [comment]
Please rebase it, and we are ready to merge.

**Comment by Random-Liu** [comment]
Apply LGTM based on https://github.com/kubernetes/node-problem-detector/pull/92#issuecomment-280138082.

Will merge this after test passed.

**Comment by Random-Liu** [comment]
> Meanwhile, should we update README that node-problem-detector can also run as a standalone daemon now? I am ok with another pr.

Actually, @andyxning updated the README.md before https://github.com/kubernetes/node-problem-detector#start-standalone

But yes, we should put more information there.

**Pull request merged**
