### PR TITLE
vendor changes for e2e tests

### PR DESCRIPTION
**Pull request by xueweiz**
This is the vendor change part for #323 , which is part of #296 

I separate out the vendor changes to make review easier. Since vendor changes are easier to review and get merged. We can then focus on the actual code changes at #323 .

### CODE REVIEW

**Comment by wangzhen127** [comment]
I am now fine with having vendor code along with the actual code change in the same PR, as long as they are separate commits. So I will review #323 in favor of this PR.

**Comment by xueweiz** [comment]
Sounds good. :) Let me close this PR. We can reopen it if you want.

(The reason that I prefer to separate them, is because if I click "Files changed" for the PR, my browser will start to freeze. I have to filter the page by commits soon, otherwise the webpage will freeze.

**Pull request closed without merging**
