### PR TITLE
add vteratipally as maintainer

### PR DESCRIPTION
**Pull request by vteratipally**

### CODE REVIEW

**Comment by Random-Liu** [comment]
Offline discussed. We will help graduate vteratipally as a reviewer first.

Thanks for the great contribution!

**Comment by vteratipally** [comment]
* Member for at least 3 months
  * Joined Kubernetes in [December 18, 2020](https://github.com/kubernetes/org/issues/2331), https://github.com/kubernetes/org/pull/2393.
* Primary reviewer for at least 5 PRs to the codebase
  * Reviewed 6 PRs: https://github.com/kubernetes/node-problem-detector/pulls?q=reviewed-by%3Avteratipally+is%3Aclosed+is%3Apr+-author%3Avteratipally
* Reviewed or merged at least 20 substantial PRs to the codebase
  * I have submitted 18 PRs: https://github.com/kubernetes/node-problem-detector/pulls?q=is%3Apr+author%3Avteratipally+is%3Aclosed
  * 2 PRs are pending.
* Knowledgeable about the codebase
  * Reviewed and participated in design discussions for gke-node-telemetry
  and knowledge transfers to new members to help contribute GKE Windows and GKE Node and Redis team. 
* Sponsored by a subproject approver
  * Requesting @Random-Liu 
  * With no objections from other approvers
* Done through PR to update the OWNERS file
  * https://github.com/kubernetes/node-problem-detector/pull/514
* May either self-nominate, be nominated by an approver in this subproject, or be nominated by a robot
  * Self nominating

**Comment by vteratipally** [comment]
gentle-reminder

**Pull request closed without merging**
