### PR TITLE
Feature support per rule interval

### PR DESCRIPTION
**Pull request by gmemcc**
Hello ! I have just added per rule interval support for CustemPluginMonitor, PTAL.

### CODE REVIEW

**Comment by wangzhen127** [comment]
Can you explain why the plugin invoke interval is not enough? Why do you need rule invoke interval?

**Comment by gmemcc** [comment]
> Can you explain why the plugin invoke interval is not enough? Why do you need rule invoke interval?

I think it would be better to let some heavy rules be invoked at a lower frequency.

**Comment by andyxning** [comment]
IIRC, we have talked about adding rule level interval before. Will check this later.

**Comment by wangzhen127** [comment]
/assign @andyxning 
/assign @Random-Liu 
/ok-to-test

Do you mean you want to use different invoke intervals for different rules of the same plugin?

**Comment by xueweiz** [comment]
This is the real failure:
> unable to create gce instance with running docker daemon for image coreos-beta-1911-2-0-v20181024.  could not create instance tmp-node-e2e-fdba7006-coreos-beta-1911-2-0-v20181024: API error: googleapi: Error 400: Invalid value for field 'resource.disks[0].initializeParams.sourceImage': 'projects/coreos-cloud/global/images/coreos-beta-1911-2-0-v20181024'. The referenced image resource cannot be found., invalid

Seems the image `coreos-beta-1911-2-0-v20181024` has been removed from `coreos-cloud`. 

Same issue is also tracked at https://github.com/kubernetes/test-infra/issues/14465, and https://github.com/kubernetes/test-infra/pull/14466 should have it fixed.

/retest

**Pull request closed without merging**
