### PR TITLE
fix wording

### PR DESCRIPTION
**Pull request by SHLo**

### CODE REVIEW

**Comment by xueweiz** [comment]
These tests are also failing on CI:
https://k8s-testgrid.appspot.com/sig-node-node-problem-detector#ci-npd-e2e-kubernetes-gce-gci

Here is the steps right before the failure ([example log](https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-npd-e2e-kubernetes-gce-gci/1232957670089035776)):

1. k8s-e2e tests asks Prow to provide a GCP project to run the tests on:
`2020/02/27 09:16:49 main.go:726: --gcp-project is missing, trying to fetch a project from boskos.`

1. Prow provided project `e2e-gce-gci-ci-serial`, and k8s-e2e tests decides to set project using command `gcloud config set project e2e-gce-gci-ci-serial`

1. However, the command failed with error:
`googlecloudsdk.core.credentials.gce.MetadataServerException: HTTP Error 400: Bad Request`

Looking at the [source code](http://testcompany.info/google-cloud-sdk/lib/googlecloudsdk/core/credentials/gce.py), it says:
```
class MetadataServerException(Error):
  """Exception for when the metadata server cannot be reached."""
```

So it seems that for some unknown reason, the Prow job container could not reach the GCE metadata server correctly.

Hi @krzyzacy , have you seen similar issues in other k8s-e2e test Prow jobs before?

**Comment by xueweiz** [comment]
Ah, I recall that recently the v0.1 and v1beta1 metadata server endpoints are [deprecated](https://cloud.google.com/compute/docs/migrating-to-v1-metadata-server). Maybe the test container was using some very old version `gcloud` that uses those deprecated metadata server endpoints?

**Comment by krzyzacy** [comment]
I think we are on our way migrating to workload identity ^^ @fejta 

https://github.com/kubernetes/test-infra/pull/16530 should hopefully fix this

**Comment by xueweiz** [comment]
Cool! Thanks for the pointer @krzyzacy !

/retest

**Comment by fejta** [comment]
a) The v1 metadata is not deprecated, however you can only depend on this if the pod meets all the following criteria:
  * Specifies a `serviceAccountName`
  * Service account name is annotated to bind with a GCP service account using [workload-identity](/workload-identity)
  * The owner of that GCP service account has applied that binding
  * The pod runs on GKE (true for all our jobs right now)

Otherwise you need to use the secret.json file that authenticates the GCP service account -- which it should already doing.


If it isn't, then it is probably a bug somewhere. A bad `gcloud` version is a possibility. It looks like the current version is 282, but some of our jobs are still using 280.

> kubernetes/test-infra#16530 should hopefully fix this

The fix here is to activate the credentials in the secret.json file before running gcloud commands... That may help here but it is a bit confusing because the GOOGLE_APPLICATION_CREDENTIALS env variable should already do this.

These jobs should not yet depend on workload identity (or the presence/absence of the metadata server)

**Pull request merged**
